stellar:
  target_address: "G_STELLAR_DEPOSIT_ADDRESS"
  delay: 10s # how often to check for new payments
  is_testnet: true # set true for stellar testnet

deposit:
  asset_owner: "G_SOME_VALID_ADDRESS"
  delay: 10s # how often to check for new assets depositable thru stellar

horizon:
  endpoint:
  signer: "S_SOME_VALID_SECRET_KEY" # Issuer of assets
