stellar:
  is_testnet: true # set true for stellar testnet

payment:
  target_address: "G_STELLAR_DEPOSIT_ADDRESS"

deposit:
  admin_signer: "S_SOME_VALID_SIGNER_SECRET_KEY" # signer of transactions

horizon:
  endpoint:
  signer: "S_SOME_VALID_SECRET_KEY" # signer for requests

log:
  level: info
  disable_sentry: true